services:
  conduit:
    build: .
    environment:
     - Data__Provider=${Data__Provider}
     - ConnectionStrings__AppDb_SqlServer=${ConnectionStrings__AppDb_SqlServer}
     - ConnectionStrings__AppDb_PostgreSql=${ConnectionStrings__AppDb_PostgreSql}
    ports:
     - "8080:8080"
