services:
  conduit:
    build: .
    environment:
     - Data__Provider=${DATA_PROVIDER}
     - ConnectionStrings__AppDb_SqlServer=${APPDB_SQLSERVER}
     - ConnectionStrings__AppDb_PostgreSql=${APPDB_POSTGRESQL}
     - ConnectionStrings__AppDb_Sqlite=${APPDB_SQLITE}
    ports:
     - "8080:8080"
